### ISSUE TITLE
Setup Users

### ISSUE THREAD

**Issue by guacs** [guacs/past-quest#1]
### Tasks
- [ ] BACKEND: Setup password hashing/verification
- [ ] BACKEND: Implement a `UserService` for CRUD of users
- [ ] BACKEND: Implement a `TokenService` for creating access and refresh tokens
- [ ] BACKEND: Implement endpoint for CRUD of users
- [ ] BACKEND: Implement login and logout endpoints
- [ ] FRONTEND: Design the UI for the login/signup pages
- [ ] FROTNEND: Implement the login and signup pages
